- name: copy rsyslog
  ansible.builtin.template:
    src: rsyslog.conf
    dest: "{{component}}.conf"

- name: Restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
