- name: Backend Playbook
  hosts: all
  become: true
  tasks:
    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Add the Appl user
      ansible.builtin.user:
        name: expense

    - name: Create Directory
      ansible.builtin.file:
        path: /app
        state: directory


#
#  Download the application code to created app directory.
#
#  curl -o /tmp/backend.zip https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
#  cd /app
#  unzip /tmp/backend.zip
#
#
#  Every application is developed by development team will have some common softwares that they use as libraries. This application also have the same way of defined dependencies in the application configuration.
#
#  Lets download the dependencies.
#
#  cd /app
#  npm install
#
#  We need to setup a new service in systemd so systemctl can manage this service
#
#  info
#  We already discussed in linux basics that advantages of systemctl managing services, Hence we are taking that approach. Which is also a standard way in the OS.
#
#  Setup SystemD Expense Backend Service
#
#  /etc/systemd/system/backend.service
#  [Unit]
#  Description = Backend Service
#
#  [Service]
#  User=expense
#  Environment=DB_HOST="<MYSQL-SERVER-IPADDRESS>"
#  ExecStart=/bin/node /app/index.js
#  SyslogIdentifier=backend
#
#  [Install]
#  WantedBy=multi-user.target
#
#  info
#  Hint! You can create file by using vim /etc/systemd/system/backend.service
#
#  Note
#  Ensure you replace <MYSQL-SERVER-IPADDRESS> with IP address
#
#  Load the service.
#
#  systemctl daemon-reload
#
#  info
#  This above command is because we added a new service, We are telling systemd to reload so it will detect new service.
#
#  Start the service.
#
#  systemctl enable backend
#  systemctl start backend
#
#  For this application to work fully functional we need to load schema to the Database.
#
#  Info
#  Schemas are usually part of application code and developer will provide them as part of development.
#
#  We need to load the schema. To load schema we need to install mysql client.
#
#  To have it installed we can use
#
#  dnf install mysql -y
#
#  Load Schema
#
#  mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pExpenseApp@1 < /app/schema/backend.sql
#
