- name: Frontend Playbook
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Remove Old content
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Create Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory

    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy file Nginx Reverse Proxy
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Start Nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
        enabled: true
        daemon_reload: true
