- name: Frontend Playbook
  hosts: all
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Start Nginx
      ansible.builtin.systemd_service:
        state: started
        name: nginx
        enabled: true
        daemon_reload: true









#    Start & Enable Nginx service
#
#    systemctl enable nginx
#    systemctl start nginx
#
#    info
#    Try to access the service once over the browser and ensure you get some default content.
#
#    Remove the default content that web server is serving.
#
#    rm -rf /usr/share/nginx/html/*
#
#    Download the frontend content
#
#    curl -o /tmp/frontend.zip https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
#
#
#    Extract the frontend content.
#
#    cd /usr/share/nginx/html
#    unzip /tmp/frontend.zip
#
#    info
#    Try to access the nginx service once more over the browser and ensure you get expense content.
#
#    Create Nginx Reverse Proxy Configuration.
#
#    vim /etc/nginx/default.d/expense.conf
#
#    Add the following content
#
#    /etc/nginx/default.d/expense.conf
#    proxy_http_version 1.1;
#
#    location /api/ { proxy_pass http://localhost:8080/; }
#
#    location /health {
#    stub_status on;
#    access_log off;
#  }
#
#    Note
#    Ensure you replace the localhost with the actual ip address of backend component server. Word localhost is just used to avoid the failures on the Nginx Server.
#
#    Restart Nginx Service to load the changes of the configuration.
#
#    systemctl restart nginx