#    - name: Create app secrets file
#      ansible.builtin.lineinfile:
#        path: ~/app.json
#        line: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False') }}"
#        create: yes


- name: Get Secrets
  hosts: localhost
  tasks:
    - name: Create common secrets file
      ansible.builtin.lineinfile:
        path: ~/{{item | split("/") | last}}.json
        line: "{{ lookup('hashi_vault', 'secret={{ item }} token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False') }}"
        create: yes
      loop:
        - common/data/common
        - expense-{{env}}/data/{{role_name}}

    - name: Create common secrets
      ansible.builtin.shell: for i in $(ls *.json);do echo -n $(cat $i); done | sed -e 's/}{/,/g' >@~secrets.json


