- name: Get Secrets
  hosts: localhost
  tasks:
    - name: Create a file
      ansible.builtin.lineinfile:
        path: /tmp/test
        line: "Username: {{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False') }}"
        create: yes