- name: Get Secrets
  hosts: localhost
  vars:
    ssh: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False') }}"
  tasks:
    - name: Create common secrets SSH file
      ansible.builtin.lineinfile:
        path: /tmp/test
        line: "Username: {{ssh.user}}"
        create: yes

