- name: Install MySQL Server 8.0.x
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    state: restarted
    name: mysqld
    enabled: true
    daemon_reload: true

- name: Set the Root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
