format_version: 10
pipelines:
  backend:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3caedef:
        git: https://github.com/s-devops-i2/expense-ansible2.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:bjZ8ZjjP3Ztd72nCFyPfzg==:6PjWkc8qW62v0c4OLABfkxNspGj4h4ufrsSjV64FNSc=
    stages:
      - test-stage1:
          environment_variables:
            env: dev
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed
