format_version: 10
pipelines:
  mysql:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3caedef:
        git: https://github.com/s-devops-i2/expense-ansible2.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:zKYUaOKHszEVTdspyFiMvw==:tFPlgZw50MsXxPhA/D2QuQXH153XOBWuE060fYAM7zU=
    stages:
      - test-stage1:
          environment_variables:
            env: dev
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash
                    run_if: passed
