- name: Remove Old content
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: absent

- name: Create Directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_user}}"



#- name: Unarchive a file that is already on the remote machine
#  ansible.builtin.unarchive:
#    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
#    dest: "{{ app_dir }}"
#    remote_src: yes
#    owner: "{{app_user}}"
#    group: "{{app_user}}"

- name: Download and Extract App content - From Artifactory
  ansible.builtin.unarchive:
    src: http://{{artifactory_user}}:{{artifactory_password}}@artifactory-internal.shujadevops.shop:8082/artifactory/expense-{{ component }}/{{APP_VERSION}}.zip
    dest: "{{ app_dir }}"
    remote_src: yes
    owner: "{{app_user}}"
    group: "{{app_user}}"




