- name: Setting up prompt for {{ component }}
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}
  when: not only_deployment | bool

- name: Install Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter
  when:  only_deployment | bool

- name: Install Logstash
  ansible.builtin.import_role:
    name: logstash
  when: logstash_config_needed and not only_deployment | bool

- name: rsyslog configuration
  ansible.builtin.import_role:
    name: rsyslog
  when: rsyslog_config_needed and not only_deployment | bool